DECLARE @PORTFOLIO INT
DECLARE @BOOK INT
DECLARE @SECTION INT
DECLARE @SIM INT
DECLARE @DATE DATETIME
DECLARE @NAV FLOAT

SET @PORTFOLIO = 43
SET @BOOK = 3
SET @SECTION = 54
SET @SIM = 32916
SET @DATE = '20100707'
SET @NAV = 1000000

DECLARE @LASTDATE DATETIME

SELECT @LASTDATE = MAX(DATE_REF) FROM NESTDB.DBO.TB023_SECURITIES_COMPOSITION
WHERE DATE_REF < @DATE
AND ID_TICKER_COMPOSITE = @SIM

SELECT	ID_TICKER,
		SIM_POSITION,
		SIM_POSITION * PRICE_CHANGE AS SIM_PNL,
		INITIAL_POSITION,
		ASSET_PNL_PC,
		ASSET_PNL_PC - SIM_POSITION * PRICE_CHANGE AS DIFF_PNL,
		INITIAL_POSITION - SIM_POSITION AS POSITION_DIFF,
		(INITIAL_POSITION - SIM_POSITION) * PRICE_CHANGE AS POS_DIFF_PNL,
		F.*
FROM
	(SELECT	E.*,
			(TR/(LAST_INDEX/LAST_PRICE)) AS PRICE,
			(LAST_PRICE - TR/(LAST_INDEX/LAST_PRICE))/LOTE_PADRAO AS PRICE_CHANGE,
			SIM_CASH_POS/((TR/(LAST_INDEX/LAST_PRICE))/LOTE_PADRAO) AS SIM_POSITION			
	FROM
		(SELECT	C.*,
				C.SIM_PERC_POS * @NAV AS SIM_CASH_POS,
				D.LOTE_PADRAO,
				NESTDB.DBO.FCN_GET_PRICE_VALUE_ONLY(ID_TICKER,@LASTDATE,101,0,2,0,0) AS TR,
				NESTDB.DBO.FCN_GET_PRICE_VALUE_ONLY(ID_TICKER,@DATE,101,0,2,0,0) AS LAST_INDEX,
				NESTDB.DBO.FCN_GET_PRICE_VALUE_ONLY(ID_TICKER,@DATE,1,0,2,0,0) AS LAST_PRICE
		FROM
			(SELECT	COALESCE(A.ID_TICKER_COMPONENT,B.[ID TICKER]) AS ID_TICKER,
					COALESCE(A.WEIGHT,0) AS SIM_PERC_POS,
					COALESCE(B.[INITIAL POSITION], 0) AS INITIAL_POSITION,
					COALESCE(B.[POSITION],0) AS POSITION,
					COALESCE(B.[CLOSE PC],0) AS CLOSE_PC,
					COALESCE(B.[COST CLOSE PC],0) AS COST_CLOSE_PC,
					COALESCE(B.[LAST],0) AS LAST,
					COALESCE(B.[ASSET P/L PC], 0) AS ASSET_PNL_PC,
					COALESCE(B.[REALIZED],0) AS REALIZED
			FROM
				(SELECT * FROM NESTDB.DBO.TB023_SECURITIES_COMPOSITION (NOLOCK)
				WHERE DATE_REF = @DATE AND ID_TICKER_COMPOSITE = @SIM) AS A
				FULL OUTER JOIN
				(SELECT * FROM NESTDB.DBO.TB000_HISTORICAL_POSITIONS (NOLOCK)
				WHERE [DATE NOW] = @DATE AND [ID PORTFOLIO] = @PORTFOLIO
				AND [ID BOOK] = @BOOK AND [ID SECTION] = @SECTION) AS B
				ON A.ID_TICKER_COMPONENT = B.[ID TICKER]) AS C
			LEFT OUTER JOIN
				NESTDB.DBO.TB001_ATIVOS (NOLOCK) AS D
			ON ID_ATIVO = ID_TICKER) AS E) AS F