
--DECLARE @TempTable TABLE(Data_Hora_Reg datetime
--			, RowNumber int
--			, MOMBZ float, MOMUS float, RATBZ float
--			, MOMBZVol float, MOMUSVol float, RATBZVol float
--			)

SELECT Data_Hora_Reg
	, ROW_NUMBER() OVER (ORDER BY Data_Hora_Reg) AS ROWNUMBER
	, SUM(CASE WHEN Id_ativo=32916 THEN Valor ELSE 0 END) AS MOMBZ
	, SUM(CASE WHEN Id_ativo=32917 THEN Valor ELSE 0 END) AS MOMUS
	, SUM(CASE WHEN Id_ativo=32921 THEN Valor ELSE 0 END) AS RATBZ
	, 0.00000 AS MOMBZVol
	, 0.00000 AS MOMUSVol
	, 0.00000 AS RATBZVol
	, 0 AS MOMBZRetPenalty
	, 0 AS MOMUSRetPenalty
	, 0 AS RATBZRetPenalty
	, 10000.0000000 AS SUMINVOL
	, 1000.000 AS MOMBZWeight
	, 1000.000 AS MOMUSWeight
	, 1000.000 AS RATBZWeight
	, 1000.000 AS SUMWeight
INTO #TempTable
FROM NESTDB.dbo.Tb050_Preco_Acoes_Onshore
WHERE Id_Ativo IN(32916,32917,32921) AND Tipo_Preco=100
GROUP BY Data_Hora_Reg

/*
INSERT INTO #TempTable SELECT '2010-06-30',MAX(ROWNUMBER)+1,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM #TempTable
INSERT INTO #TempTable SELECT '2010-07-01',MAX(ROWNUMBER)+1,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM #TempTable
INSERT INTO #TempTable SELECT '2010-07-02',MAX(ROWNUMBER)+1,0,0,0,0,0,0,0,0,0,0,0,0,0,0 FROM #TempTable
*/

CREATE INDEX TempIndex ON #TempTable(ROWNUMBER)

UPDATE #TempTable SET 
	MOMBZVol=COALESCE((SELECT STDEV(MOMBZ)*SQRT(252) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-30),0)
	, MOMUSVol=COALESCE((SELECT STDEV(MOMUS)*SQRT(252) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-30),0)
	, RATBZVol=COALESCE((SELECT STDEV(RATBZ)*SQRT(252) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-30),0)
	, MOMBZRetPenalty=CASE WHEN (SELECT MIN(MOMBZ) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-3)<-0.01 THEN 1 ELSE 0 END 
	, MOMUSRetPenalty=CASE WHEN (SELECT MIN(MOMUS) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-3)<-0.01 THEN 1 ELSE 0 END 
	, RATBZRetPenalty=CASE WHEN (SELECT MIN(RATBZ) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-3)<-0.01 THEN 1 ELSE 0 END 
	--, RATBZWeight=CASE WHEN (SELECT MIN(RATBZ) FROM #TempTable B WHERE RowNumber<=A.RowNumber AND RowNumber>A.RowNumber-3)<-0.01 THEN 1 ELSE 0 END 
FROM #TempTable A

UPDATE #TempTable SET 
	SUMINVOL = CASE WHEN MOMBZVol<>0 THEN 1/MOMBZVol ELSE 0 END
				+ CASE WHEN MOMUSVol<>0 THEN 1/MOMUSVol ELSE 0 END
				+ CASE WHEN RATBZVol<>0 THEN 1/RATBZVol ELSE 0 END + 0.0000001

UPDATE #TempTable SET 
	MOMBZWeight=ROUND(CASE WHEN MOMBZVol<>0 THEN 1/MOMBZVol ELSE 0 END / SUMINVOL * CASE WHEN MOMBZRetPenalty=1 THEN 0.5 ELSE 1 END / 0.05,0) * 0.05
	, MOMUSWeight=ROUND(CASE WHEN MOMUSVol<>0 THEN 1/MOMUSVol ELSE 0 END / SUMINVOL * CASE WHEN MOMUSRetPenalty=1 THEN 0.5 ELSE 1 END / 0.05,0) * 0.05
	, RATBZWeight=ROUND(CASE WHEN RATBZVol<>0 THEN 1/RATBZVol ELSE 0 END / SUMINVOL * CASE WHEN RATBZRetPenalty=1 THEN 0.5 ELSE 1 END / 0.05,0) * 0.05

UPDATE #TempTable SET 
	SUMWeight=MOMBZWeight+MOMUSWeight+RATBZWeight

SELECT *
FROM #TempTable ORDER BY Data_Hora_Reg

DROP TABLE #TempTable