SELECT A.CODCVM, A.KnowDateTime, B.CODCONTA, B.IsConsolidated, B.DESCONTA, A.DT_ATU_F, B.Valor1--, RAZAO_SOC, TRIM, DT_ANT_F , B.*
FROM nestother.dbo.Tb023_CVM_ITR_HDR A
LEFT JOIN nestother.dbo.Tb025_CVM_ITR_DATA B
ON A.ZipName=B.ZipName
WHERE A.CODCVM=4820 AND B.FileName='ITRCDERE.001' AND B.CODCONTA IN ('3.15')--('3.05', '3.07', '3.15')
ORDER BY DT_ATU_F


SELECT A.CODCVM, A.KnowDateTime, B.CODCONTA, B.IsConsolidated, B.DESCONTA, DT2C3Q9, B.VALOR3, DT2C2Q9, B.VALOR2, DT2C1Q9, B.VALOR1--, B.*
FROM nestother.dbo.Tb023_CVM_DFP_HDR A
LEFT JOIN nestother.dbo.Tb025_CVM_DFP_DATA B
ON A.ZipName=B.ZipName
WHERE A.CODCVM=4820 AND B.FileName='DFPCDERE.001' AND B.CODCONTA IN ('3.15')--('3.05', '3.07', '3.15')
ORDER BY DT2C3Q9

/*
ITRCDERE
ITRDEREE


DFPCDERE
DFPDEREE
*/

SELECT DT2C3Q9, MAX(CASE WHEN B.FileName LIKE '%CDER%' THEN B.FileName ELSE null END)
FROM nestother.dbo.Tb023_CVM_DFP_HDR A
LEFT JOIN nestother.dbo.Tb025_CVM_DFP_DATA B
ON A.ZipName=B.ZipName
WHERE A.CODCVM=4820 
GROUP BY DT2C3Q9
ORDER BY DT2C3Q9


SELECT A.DATAREF, A.STATUS, MAX(CASE WHEN B.FileName LIKE '%CDER%' THEN B.FileName ELSE null END)
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG A
LEFT JOIN nestother.dbo.Tb025_CVM_ITR_DATA B
ON A.ZipName=B.ZipName
WHERE A.CODCVM=4820 
GROUP BY A.DATAREF, A.STATUS
ORDER BY A.DATAREF, A.STATUS


-- MARFRIG
SELECT *
FROM nestother.dbo.Tb022_CVM_ITR_CONFIG 
WHERE CODCVM=20788
ORDER BY DATAREF

-- BRASKEM
SELECT *
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG 
WHERE CODCVM=4820
ORDER BY DATAREF


SELECT ZipName
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG
WHERE ZipName not in (SELECT ZipName FROM nestother.dbo.Tb025_CVM_DFP_DATA WHERE FileName LIKE '%BP%' GROUP BY ZipName)
GROUP BY ZipName


SELECT COUNT(*) FROM (SELECT ZipName FROM nestother.dbo.Tb025_CVM_DFP_DATA WHERE FileName LIKE '%DER%' GROUP BY ZipName) AS A