using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Threading;
using QuickFix;
using NestDLL;
using NCommonTypes;

namespace newNFIXConn
{
    /// <summary>
    /// FIX interface to send the orders generated by strategies
    /// </summary>
    public class newFIXConn //: MessageCracker, QuickFix.Application, IDisposable
    {
        //    private SessionSettings _settings;
        //    private FileStoreFactory _store;
        //    private FileLogFactory _logs;
        //    private MessageFactory _messages;
        //    private SocketInitiator _initiator;
        //    private string _QFConfig;
        //    private SessionID _ID_Session = null;
        //    public int ordID = 0;
        //    private bool _IsAliveSession = false;
        //    public bool IsAliveSession
        //    {
        //        get { return _IsAliveSession; }
        //    }


        //    public SortedDictionary<string, Order> OrderContainer = new SortedDictionary<string, Order>();
        //    private Mutex MutexOrderContainer = new Mutex();

        //    /// <summary>
        //    /// Event executed when a Fill or Partial Fill Execution Report is received
        //    /// </summary>
        //    public event EventHandler OnUpdate;
        //    public event EventHandler OnExecutionReport;

        //    #region Properties

        //    /// <summary>
        //    /// Full path to QuickFix configuration File
        //    /// </summary>
        //    public string QFConfig
        //    {
        //        get
        //        {
        //            return _QFConfig;
        //        }
        //    }

        //    /// <summary>
        //    /// Unique session identifier
        //    /// </summary>
        //    public QuickFix.SessionID ID_Session
        //    {
        //        get
        //        {
        //            return _ID_Session;
        //        }
        //    }

        //    #endregion

        //    #region Constructors

        //    /// <summary>
        //    /// Create instance of FIX class
        //    /// </summary>
        //    /// <param name="_qfConfig">QuickFix configuration file full path</param>
        //    public newFIXConn(string _qfConfig)
        //    {
        //        _QFConfig = _qfConfig;

        //        try
        //        {
        //            _settings = new SessionSettings(QFConfig);
        //            _store = new FileStoreFactory(_settings);
        //            _logs = new FileLogFactory(_settings);
        //            _messages = new DefaultMessageFactory();
        //            _initiator = new SocketInitiator(this, _store, _settings, _logs, _messages);

        //            _initiator.start();
        //        }
        //        catch (Exception e)
        //        {
        //            throw new Exception("Unable to create instance of class FIX", e);
        //        }//catch



        //    }//FIX

        //    #endregion

        //    #region Send Messages

        //    /*
        //    public string sendOrder(int ID_Ticker, int Qty, double price, int IdPortfolio, int IdBook, int IdSection)
        //    {
        //        string result = sendOrder(ID_Ticker, Qty,price, IdPortfolio, IdBook, IdSection, "");

        //        return result;
        //    }

        //    public string sendOrder(int ID_Ticker, int Qty, double price, int IdPortfolio, int IdBook, int IdSection, bool DontMatch)
        //    {
        //        string OrderType = (Qty >= 0 ? NCommonTypes.NEnuns.NOrderType.Buy : NCommonTypes.NEnuns.NOrderType.Sell);

        //        string result = sendOrder(nextClOrderID(), ID_Ticker, Qty, price, IdPortfolio, IdBook, IdSection, "", OrderType, DontMatch);

        //        return result;
        //    }

        //    public string sendOrder(int ID_Ticker, int Qty, double price, int IdPortfolio, int IdBook, int IdSection, string extension)
        //    {
        //        string OrderType = (Qty >= 0 ? NCommonTypes.NEnuns.NOrderType.Buy : NCommonTypes.NEnuns.NOrderType.Sell);

        //        string result = sendOrder(nextClOrderID(), ID_Ticker, Qty, price, IdPortfolio, IdBook, IdSection, extension,OrderType, false);

        //        return result;
        //    }

        //    public string sendOrder(string OrderID, int ID_Ticker, int Qty, double price, int IdPortfolio, int IdBook, int IdSection)
        //    {

        //        string OrderType = (Qty >= 0 ? NCommonTypes.NEnuns.NOrderType.Buy : NCommonTypes.NEnuns.NOrderType.Sell);

        //        string result = sendOrder(OrderID, ID_Ticker, Qty, price, IdPortfolio, IdBook, IdSection,"",OrderType, false);

        //        return result;
        //    }
        //    */

        //    public string sendOrder(string OrderPrefix, int ID_Ticker, int Qty, double price, int IdPortfolio, int IdBook, int IdSection, string extension, string OrderType, bool DontMatch)
        //    {
        //        string ClOrdID;

        //        Order curOrder = new Order(OrderPrefix);
        //        curOrder.OnNewOrder += new EventHandler(OnFixMessage);
        //        curOrder.OnOrderUpdate += new EventHandler(OnOrderUpdate);
        //        OnExecutionReport += new EventHandler(curOrder.OnFixMessage);            
        //        ClOrdID = curOrder.CreateNewOrder(ID_Ticker, Qty, price, IdPortfolio, IdBook, IdSection, extension, OrderType, DontMatch);

        //        OrderContainer.Add(ClOrdID, curOrder);

        //        return ClOrdID;
        //    }

        //    void OnOrderUpdate(object sender, EventArgs e)
        //    {
        //        if (OnUpdate != null)
        //        {
        //            OnUpdate(sender, e);
        //        }
        //    }

        //    private void OnFixMessage(object sender, EventArgs e)
        //    {
        //        FixMsgArgs curMsg = (FixMsgArgs)e;

        //        if (curMsg.OrderType == "NEWORDERSINGLE")
        //        {
        //            QuickFix42.NewOrderSingle curOrder = curMsg.OrdSingle;
        //            Session.sendToTarget(curOrder, _ID_Session);
        //        }
        //        else if (curMsg.OrderType == "ORDERCANCEL")
        //        {
        //            QuickFix42.OrderCancelRequest curOrder = curMsg.OrdCancel;
        //            Session.sendToTarget(curOrder, _ID_Session);
        //        }
        //    }     


        //    public void cancelAllOrders(int ID_Ticker)
        //    {
        //        foreach (Order ord in OrderContainer.Values)
        //        {
        //            if (ord.IdSecurity == ID_Ticker)
        //            {
        //                cancelOrder(ord.OrigClOrdID);
        //            }
        //        }
        //    }

        //    public bool cancelOrder(string clOrdID)
        //    {
        //        bool result = false;

        //        if (OrderContainer.ContainsKey(clOrdID))
        //        {
        //            result = OrderContainer[clOrdID].CancelOrder();                
        //        }

        //        return result;
        //    }



        //    #endregion

        //    #region Receive Messages        

        //    public override void onMessage(QuickFix42.ExecutionReport message, SessionID session)
        //    {
        //        if (OnExecutionReport != null)
        //        {
        //            FixMsgArgs recMessage = new FixMsgArgs();
        //            recMessage.OrderType = "EXECUTIONREPORT";
        //            recMessage.ExecReport = message;

        //            OnExecutionReport(this, recMessage);
        //        }           
        //    }//onMessage(QuickFix42.ExecutionReport message, SessionID session)        

        //    #endregion

        //    #region QuickFix Events
        //    /// <summary>
        //    /// Called on FIX session creation
        //    /// </summary>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void onCreate(SessionID sessionID)
        //    {
        //        _ID_Session = sessionID;
        //    }

        //    /// <summary>
        //    /// Called on successful logon
        //    /// </summary>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void onLogon(SessionID sessionID)
        //    {
        //        _IsAliveSession = true;
        //    }

        //    /// <summary>
        //    /// Called when connection ends
        //    /// </summary>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void onLogout(SessionID sessionID)
        //    {
        //        _IsAliveSession = false;
        //    }

        //    /// <summary>
        //    /// Called before the application sends a session message
        //    /// </summary>
        //    /// <param name="message">FIX message</param>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void toAdmin(Message message, SessionID sessionID)
        //    {
        //    }

        //    /// <summary>
        //    /// Called when a session message is received
        //    /// </summary>
        //    /// <param name="message">FIX message</param>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void fromAdmin(Message message, SessionID sessionID)
        //    {
        //        crack(message, sessionID);
        //    }

        //    /// <summary>
        //    /// Called before the application sends an application message
        //    /// </summary>
        //    /// <param name="message">FIX message</param>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void toApp(Message message, SessionID sessionID)
        //    {
        //        //SenderSubID _senderSubId = new SenderSubID("UA");

        //        //if (!message.isSetField(_senderSubId)) { message.setField(_senderSubId); }
        //    }

        //    /// <summary>
        //    /// Called when an application message is received
        //    /// </summary>
        //    /// <param name="message">FIX message</param>
        //    /// <param name="sessionID">Identifies uniquely the session</param>
        //    public void fromApp(Message message, SessionID sessionID)
        //    {
        //        try
        //        {
        //            crack(message, sessionID);
        //        }
        //        catch (Exception e)
        //        {
        //            Console.WriteLine(e.ToString());
        //            Console.WriteLine(message.ToXML());
        //        }
        //    }
        //    #endregion

        //    #region Disposable Region

        //    /// <summary>
        //    /// Disposes FIX class
        //    /// </summary>
        //    public void Dispose()
        //    {
        //        _initiator.stop();
        //    }//Dispose



        //    #endregion

        //}//FixConn

        //public class Order
        //{
        //    #region OrderProperties region

        //    private string _OrigClOrdID;
        //    private string _ClOrdID;
        //    private int _IdSecurity;
        //    private string _Symbol;
        //    private Side _Side;
        //    private int _OrdQty;
        //    private double _OrdPrice;
        //    private int _UnordQty;
        //    private int _LeavesQty;
        //    private int _CumQty;
        //    private int _Outs;
        //    private double _AvgPrice;
        //    private OrdStatus _OrdStatus;
        //    private int _IdPortfolio;
        //    private int _IdBook;
        //    private int _IdSection;
        //    private bool _DontMatch;
        //    private bool _CanReplace;

        //    public string OrigClOrdID { get { return _OrigClOrdID; } }
        //    public string ClOrdID { get { return _ClOrdID; } }
        //    public int IdSecurity { get { return _IdSecurity; } }
        //    public string Symbol { get { return _Symbol; } }
        //    public string OrdSide
        //    {
        //        get
        //        {
        //            string result = "";

        //            if (_Side.getValue() == Side.BUY) { result = "BUY"; }
        //            else if (_Side.getValue() == Side.SELL) { result = "SELL"; }
        //            else if (_Side.getValue() == Side.SELL_SHORT) { result = "SELL_SHORT"; }                

        //            return result;
        //        }
        //    }
        //    public int OrdQty { get { return _OrdQty; } }
        //    public double OrdPrice { get { return _OrdPrice; } }
        //    public int UnordQty { get { return _UnordQty; } }
        //    public int curLeavesQty { get { return _LeavesQty; } }
        //    public int curCumQty { get { return _CumQty; } }
        //    public int Outs { get { return _Outs; } }
        //    public double AvgPrice { get { return _AvgPrice; } }
        //    public string curOrdStatus
        //    {
        //        get
        //        {
        //            string result = "";

        //            if (_OrdStatus.getValue() == OrdStatus.PENDING_NEW) { result = "PENDING_NEW"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.NEW) { result = "NEW"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.PARTIALLY_FILLED) { result = "PARTIALLY_FILLED"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.FILLED) { result = "FILLED"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.REPLACED) { result = "REPLACED"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.CANCELED) { result = "CANCELED"; }
        //            else if (_OrdStatus.getValue() == OrdStatus.REJECTED) { result = "REJECTED"; }               

        //            return result;
        //        }
        //    }
        //    public int IdPortfolio { get { return _IdPortfolio; } }
        //    public int IdBook { get { return _IdBook; } }
        //    public int IdSection { get { return _IdSection; } }
        //    public bool DontMatch { get { return _DontMatch; } }
        //    public bool CanReplace { get { return _CanReplace; } }

        //    private string OrderPrefix;        

        //    #endregion

        //    #region Events region

        //    public event EventHandler OnNewOrder;
        //    public event EventHandler OnOrderUpdate;

        //    #endregion        

        //    private SortedDictionary<string, FixMsgArgs> SentMessages = new SortedDictionary<string, FixMsgArgs>();
        //    private SortedDictionary<string, FixMsgArgs> ReceivedMessages = new SortedDictionary<string, FixMsgArgs>();

        //    public Order(string _OrderPrefix) 
        //    {
        //        OrderPrefix = _OrderPrefix;
        //    }

        //    public string CreateNewOrder(int IdSecurity, int Qty, double price, int IdPortfolio, int IdBook, int IdSection, string extension, string OrderType, bool DontMatch)
        //    {
        //        _OrigClOrdID = nextClOrderID();
        //        _ClOrdID = _OrigClOrdID;
        //        _IdSecurity = IdSecurity;
        //        _Symbol = getSymbol(_IdSecurity);

        //        if (extension != "")
        //        {
        //            _Symbol = _Symbol.Split('.')[0] + "." + extension;
        //        }

        //        if (Qty > 0 && (OrderType == NCommonTypes.NEnuns.NOrderType.Buy || OrderType == NCommonTypes.NEnuns.NOrderType.BuyToCover))
        //        {
        //            _Side = new Side(Side.BUY);
        //        }
        //        else if (Qty < 0)
        //        {
        //            if (OrderType == NCommonTypes.NEnuns.NOrderType.Sell)
        //            {
        //                _Side = new Side(Side.SELL);
        //            }
        //            else if (OrderType == NCommonTypes.NEnuns.NOrderType.SellShort)
        //            {
        //                _Side = new Side(Side.SELL_SHORT);
        //            }
        //        }

        //        _OrdQty = Qty;
        //        _OrdPrice = price;
        //        _UnordQty = _OrdQty;
        //        _LeavesQty = 0;
        //        _CumQty = 0;
        //        _AvgPrice = 0;
        //        _OrdStatus = new OrdStatus(OrdStatus.PENDING_NEW);
        //        _IdPortfolio = IdPortfolio;
        //        _IdBook = IdBook;
        //        _IdSection = IdSection;
        //        _DontMatch = DontMatch;
        //        _CanReplace = false;

        //        SendNewOrder();

        //        return _OrigClOrdID;
        //    }
        //    private void SendNewOrder()
        //    {
        //        ClOrdID qfClOrdID = new ClOrdID(_ClOrdID);
        //        HandlInst qfHandlInst = new HandlInst(HandlInst.AUTOMATED_EXECUTION_ORDER_PRIVATE);            
        //        Symbol qfSymbol = new Symbol(_Symbol);
        //        Side qfSide = _Side;          
        //        TransactTime qfTTime = new TransactTime(DateTime.Now);
        //        OrdType qfOrdType = new OrdType();

        //        if (_OrdPrice > 0)
        //        {
        //            qfOrdType.setValue(OrdType.LIMIT);
        //        }
        //        else
        //        {
        //            qfOrdType.setValue(OrdType.MARKET);
        //        }

        //        OrderQty qfQty = new OrderQty((double)Math.Abs(_UnordQty));
        //        Price qfPrice = new Price();

        //        QuickFix42.NewOrderSingle orderSingle = new QuickFix42.NewOrderSingle(qfClOrdID,
        //                                                                              qfHandlInst,
        //                                                                              qfSymbol,
        //                                                                              qfSide,
        //                                                                              qfTTime,
        //                                                                              qfOrdType);

        //        orderSingle.set(qfQty);

        //        if (_OrdPrice > 0)
        //        {
        //            qfPrice.setValue(_OrdPrice);
        //            orderSingle.set(qfPrice);
        //        }
        //        else if (_OrdPrice == -2)
        //        {
        //            orderSingle.setString(9304, "Y");
        //        }
        //        else
        //        {
        //            orderSingle.setString(9304, "N");
        //        }

        //        orderSingle.setInt(9305, _IdBook);
        //        orderSingle.setInt(9306, _IdSection);
        //        orderSingle.setInt(9307, _IdPortfolio);
        //        if (_DontMatch) { orderSingle.setString(9308, "Y"); } else { orderSingle.setString(9308, "N"); }

        //        if (OnNewOrder != null)
        //        {
        //            FixMsgArgs OrderToSend = new FixMsgArgs();
        //            OrderToSend.OrderType = "NEWORDERSINGLE";
        //            OrderToSend.OrdSingle = orderSingle;

        //            SentMessages.Add(qfClOrdID.getValue(), OrderToSend);

        //            OnNewOrder(this, OrderToSend);

        //        }

        //        ReportUpdate();
        //    }
        //    public bool CancelOrder()
        //    {
        //        bool result = false;

        //        if (_CanReplace)
        //        {
        //            QuickFix.OrigClOrdID qfOrigClOrdID = new QuickFix.OrigClOrdID(_ClOrdID);
        //            QuickFix.ClOrdID qfClOrdID = new QuickFix.ClOrdID(nextClOrderID());
        //            QuickFix.Symbol qfSymbol = new QuickFix.Symbol(_Symbol);
        //            QuickFix.Side qfSide = _Side;
        //            QuickFix.TransactTime qfTTime = new TransactTime(DateTime.Now);
        //            QuickFix.OrderQty qfOrderQty = new OrderQty(_LeavesQty);

        //            QuickFix42.OrderCancelRequest cancel = new QuickFix42.OrderCancelRequest(qfOrigClOrdID, qfClOrdID, qfSymbol, qfSide, qfTTime);
        //            cancel.set(qfOrderQty);

        //            if (OnNewOrder != null)
        //            {
        //                FixMsgArgs OrderToSend = new FixMsgArgs();
        //                OrderToSend.OrderType = "ORDERCANCEL";
        //                OrderToSend.OrdCancel = cancel;

        //                SentMessages.Add(qfClOrdID.getValue(), OrderToSend);

        //                OnNewOrder(this, OrderToSend);
        //            }

        //            _CanReplace = false;
        //            result = true;
        //        }

        //        return result;
        //    }

        //    public void OnFixMessage(object sender, EventArgs e)
        //    {
        //        FixMsgArgs curMsg = (FixMsgArgs)e;

        //        if (curMsg.OrderType == "EXECUTIONREPORT")
        //        {
        //            string clOrd = curMsg.ExecReport.getClOrdID().getValue();
        //            string symbol = curMsg.ExecReport.getSymbol().getValue();

        //            if (SentMessages.ContainsKey(clOrd))
        //            {
        //                if (symbol == _Symbol)
        //                {
        //                    //ReceivedMessages.Add(clOrd, curMsg);
        //                    ProcessExecutionReport(curMsg.ExecReport);
        //                }
        //            }
        //        }
        //    }

        //    public void ProcessExecutionReport(QuickFix42.ExecutionReport message)
        //    {
        //        ClOrdID qfClOrdID = message.getClOrdID();
        //        ExecTransType qfTransType = message.getExecTransType();
        //        ExecType qfExecType = message.getExecType();
        //        OrdStatus qfOrdStatus = message.getOrdStatus();
        //        LeavesQty qfLeavesQty = message.getLeavesQty();
        //        CumQty qfCumQty = message.getCumQty();
        //        AvgPx qfAvgPx = message.getAvgPx();
        //        OrderQty qfOrderQty = message.getOrderQty();

        //        if (qfTransType.getValue() == ExecTransType.NEW)
        //        {
        //            if (qfExecType.getValue() == ExecType.NEW)
        //            {
        //                _ClOrdID = qfClOrdID.getValue();
        //                _LeavesQty = (int)qfLeavesQty.getValue();
        //                _CumQty = (int)qfCumQty.getValue();
        //                _AvgPrice = qfAvgPx.getValue();
        //                _UnordQty = _OrdQty - _LeavesQty - _CumQty;
        //                _OrdStatus = qfOrdStatus;
        //                _CanReplace = true;
        //            }
        //            else if (qfExecType.getValue() == ExecType.PARTIAL_FILL || qfExecType.getValue() == ExecType.FILL)
        //            {
        //                _LeavesQty = (int)qfLeavesQty.getValue();
        //                _CumQty = (int)qfCumQty.getValue();
        //                _AvgPrice = qfAvgPx.getValue();
        //                _OrdStatus = qfOrdStatus;
        //            }
        //            else if (qfExecType.getValue() == ExecType.CANCELED)
        //            {
        //                _OrdStatus = qfOrdStatus;
        //                _LeavesQty = (int)qfLeavesQty.getValue();
        //                _CumQty = (int)qfCumQty.getValue();
        //                _Outs = (int)(qfOrderQty.getValue() - qfCumQty.getValue());
        //            }
        //            else
        //            {
        //                int a = 0;
        //            }
        //        }
        //        else
        //        {
        //            int a = 0;
        //        }

        //        ReportUpdate();                
        //    }

        //    public void ReportUpdate()
        //    {
        //        if (OnOrderUpdate != null)
        //        {
        //            NCommonTypes.FIXOrder UpdateOrderArgs = new NCommonTypes.FIXOrder(IdSecurity, Symbol, OrdSide, OrdQty, OrdPrice);

        //            UpdateOrderArgs.ClOrdID = ClOrdID;
        //            UpdateOrderArgs.OrigClOrdID = OrigClOrdID;

        //            UpdateOrderArgs.strStatus = curOrdStatus;

        //            UpdateOrderArgs.Done = curCumQty;
        //            UpdateOrderArgs.Cancelled = Outs;                

        //            UpdateOrderArgs.ExecPrice = AvgPrice;


        //            OnOrderUpdate(this, UpdateOrderArgs);
        //        }
        //    }

        //    private string nextClOrderID()
        //    {
        //        return OrderPrefix + getNextOrdID().ToString("000000");
        //    }        
        //    private int getNextOrdID()
        //    {
        //        int ordID;

        //        if (DateTime.Today.Equals(NFIXConn.Properties.Settings.Default.LastClOrdIDDate))
        //        {
        //            ordID = NFIXConn.Properties.Settings.Default.LastClOrdID;
        //            ordID++;
        //            NFIXConn.Properties.Settings.Default.LastClOrdID = ordID;
        //            NFIXConn.Properties.Settings.Default.Save();
        //        }
        //        else
        //        {
        //            NFIXConn.Properties.Settings.Default.LastClOrdIDDate = DateTime.Today;
        //            ordID = 1;
        //            NFIXConn.Properties.Settings.Default.LastClOrdID = ordID;
        //            NFIXConn.Properties.Settings.Default.Save();
        //        }

        //        return ordID;
        //    }
        //    private string getSymbol(int ID_Ticker)
        //    {
        //        string SQLExpresion = "SELECT EXCHANGETICKER FROM NESTSRV06.NESTDB.DBO.TB001_SECURITIES WITH(NOLOCK) WHERE IDSECURITY = " + ID_Ticker.ToString();

        //        string result = "";

        //        using (newNestConn conn = new newNestConn(true))
        //        {
        //            if ((result = conn.Execute_Query_String(SQLExpresion)) == "")
        //            {
        //                throw new System.NotImplementedException();
        //            }
        //        }

        //        return result;
        //    }
        //}

        //public class FixMsgArgs : EventArgs
        //{
        //    public string OrderType;
        //    public QuickFix42.NewOrderSingle OrdSingle;
        //    public QuickFix42.OrderCancelRequest OrdCancel;
        //    public QuickFix42.OrderCancelReplaceRequest OrdReplace;
        //    public QuickFix42.ExecutionReport ExecReport;
        //    public QuickFix42.OrderCancelReject CancelReject;               
        //}

        //public class newOrder
        //{
        //    private ClOrdID _ClOrdID;
        //    public ClOrdID ClOrdID
        //    {
        //        get { return _ClOrdID; }
        //    }

        //    private OrigClOrdID _OrigClOrdID;
        //    public OrigClOrdID OrigClOrdID
        //    {
        //        get { return _OrigClOrdID; }
        //    }

        //    private int _ID_Ticker;
        //    public int ID_Ticker
        //    {
        //        get
        //        {
        //            return _ID_Ticker;
        //        }
        //    }

        //    private Symbol _Symbol;
        //    public Symbol Symbol
        //    {
        //        get { return _Symbol; }
        //        set { _Symbol = value; }
        //    }

        //    private Side _Side;
        //    public Side Side
        //    {
        //        get { return _Side; }
        //        set { _Side = value; }
        //    }

        //    private OrderQty _OrderQty;
        //    public OrderQty OrderQty
        //    {
        //        get { return _OrderQty; }
        //        set { _OrderQty = value; }
        //    }

        //    private Price _Price;

        //    private OrdStatus _Status;
        //    public OrdStatus Status
        //    {
        //        get { return _Status; }
        //        set { _Status = value; }
        //    }

        //    private CumQty _CumQty;                     

        //    public newOrder(ClOrdID clOrdID, int id_Ticker, Symbol symbol, Side side, OrderQty orderQty, Price price)
        //    {
        //        _ClOrdID = clOrdID;
        //        _ID_Ticker = id_Ticker;
        //        _Symbol = symbol;
        //        _Side = side;
        //        _OrderQty = orderQty;
        //        _Price = price;

        //        _OrigClOrdID = new OrigClOrdID(clOrdID.getValue());
        //        _CumQty = new CumQty(0);
        //        _Status = new OrdStatus(OrdStatus.NEW);
        //    }        

        //    /// <summary>
        //    /// Fills the order with the number of last shares received on an Execution Report
        //    /// </summary>
        //    /// <param name="clOrdId">ClOrdId of the order to be filled</param>
        //    /// <param name="lastShares">Qty of shares to fill</param>
        //    /// <param name="cumQty">Total of shares filled</param>
        //    public void FillOrder(ClOrdID clOrdId, LastShares lastShares, CumQty cumQty)
        //    {
        //        if (clOrdId.getValue() == ClOrdID.getValue())
        //        {
        //            _CumQty.setValue(_CumQty.getValue() + lastShares.getValue());
        //            if (_CumQty.getValue() != cumQty.getValue())
        //            {
        //                Console.WriteLine("Last shares do not fill Order to the expected CumQty. Received: " + cumQty.ToString() + " Expected: " + _CumQty.ToString());
        //            }
        //        }
        //        else
        //        {
        //            throw new Exception("Incorrect ClOrdID on order fill. Received: " + clOrdId.ToString() + " Expected: " + ClOrdID.ToString());
        //        }
        //    }

        //    /// <summary>
        //    /// Changes the order´s status. Throws exception if the new status is unreachable from the current status
        //    /// </summary>
        //    /// <param name="ordStatus">New order status</param>
        //    public void ChangeStatus(OrdStatus ordStatus)
        //    {
        //        bool canChange = false;

        //        switch (Status.getValue())
        //        {
        //            case OrdStatus.PENDING_NEW:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.NEW:
        //                    case OrdStatus.REJECTED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.NEW:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.NEW:
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                    case OrdStatus.FILLED:
        //                    case OrdStatus.DONE_FOR_DAY:
        //                    case OrdStatus.PENDING_CANCEL:
        //                    case OrdStatus.PENDING_REPLACE:
        //                    case OrdStatus.REPLACED:
        //                    case OrdStatus.STOPPED:
        //                    case OrdStatus.REJECTED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.PARTIALLY_FILLED:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                    case OrdStatus.FILLED:
        //                    case OrdStatus.DONE_FOR_DAY:
        //                    case OrdStatus.PENDING_CANCEL:
        //                    case OrdStatus.PENDING_REPLACE:
        //                    case OrdStatus.CANCELED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.FILLED:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                    case OrdStatus.FILLED:
        //                    case OrdStatus.PENDING_REPLACE:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.DONE_FOR_DAY:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.PENDING_CANCEL:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.NEW:
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                    case OrdStatus.FILLED:
        //                    case OrdStatus.PENDING_CANCEL:
        //                    case OrdStatus.CANCELED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.PENDING_REPLACE:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.NEW:
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                    case OrdStatus.FILLED:
        //                    case OrdStatus.PENDING_REPLACE:
        //                    case OrdStatus.REPLACED:
        //                    case OrdStatus.CANCELED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.REPLACED:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.STOPPED:
        //                switch (ordStatus.getValue())
        //                {
        //                    case OrdStatus.PARTIALLY_FILLED:
        //                        canChange = true;
        //                        break;
        //                    default:
        //                        canChange = false;
        //                        break;
        //                }
        //                break;
        //            case OrdStatus.CANCELED:
        //            case OrdStatus.REJECTED:
        //            default:
        //                canChange = false;
        //                break;
        //        }

        //        if (canChange)
        //        {
        //            Status = ordStatus;
        //        }
        //        else
        //        {
        //            //throw new Exception("New order status unreachable. Current Status: " + Status.getValue() + " New Status: " + ordStatus.getValue());
        //        }
        //    }
        //}//Order  
    }
}
