// ------------------------------------------------------------------------------
//     This code was generated by 
//     9Rays.Net Decompiler.Net services Evaluation
//     ver.5.4.6.0
//     http://www.9rays.net
//     Copyright 2009 9Rays.Net All rights reserved.
//     Evaluation version: decompiles about 50% of methods, properties and events.
// ------------------------------------------------------------------------------

namespace SGN
{

  public class partial frmPositions2 : System.Windows.Forms.Form
  {
    private void InitializeComponent()
    {
      // Evaluation version.
}
    protected override void Dispose(bool disposing)
    {
      bool bl;
      bl = !disposing ? true : this.components == null;
      if (bl)
      {
        goto ILO_0022;
      }
      this.components.Dispose();
    ILO_0022:
      base.Dispose(disposing);
      return;
    }
    private System.ComponentModel.IContainer components;
  }
}
