//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInterfaces.AtivosService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoWebService", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public partial class RetornoWebService : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string MensagemField;
        
        private ServiceInterfaces.AtivosService.eStatusRetorno StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.AtivosService.eStatusRetorno Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eStatusRetorno", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public enum eStatusRetorno : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArquivoBoletoDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    public partial class ArquivoBoletoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescStatusArquivoField;
        
        private System.DateTime DtUploadField;
        
        private int IdArquivoField;
        
        private int IdGestorField;
        
        private int NumRegistrosErroField;
        
        private int NumRegistrosSucessoField;
        
        private int StatusArquivoField;
        
        private int TotalRegistrosField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.TipoBoleto> enumTipoBoletoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescStatusArquivo
        {
            get
            {
                return this.DescStatusArquivoField;
            }
            set
            {
                this.DescStatusArquivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtUpload
        {
            get
            {
                return this.DtUploadField;
            }
            set
            {
                this.DtUploadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArquivo
        {
            get
            {
                return this.IdArquivoField;
            }
            set
            {
                this.IdArquivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGestor
        {
            get
            {
                return this.IdGestorField;
            }
            set
            {
                this.IdGestorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumRegistrosErro
        {
            get
            {
                return this.NumRegistrosErroField;
            }
            set
            {
                this.NumRegistrosErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumRegistrosSucesso
        {
            get
            {
                return this.NumRegistrosSucessoField;
            }
            set
            {
                this.NumRegistrosSucessoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusArquivo
        {
            get
            {
                return this.StatusArquivoField;
            }
            set
            {
                this.StatusArquivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRegistros
        {
            get
            {
                return this.TotalRegistrosField;
            }
            set
            {
                this.TotalRegistrosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.TipoBoleto> enumTipoBoleto
        {
            get
            {
                return this.enumTipoBoletoField;
            }
            set
            {
                this.enumTipoBoletoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoBoleto", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum TipoBoleto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RendaFixa = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RendaVariavel = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Futuro = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cambio = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Termo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swap = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adelic = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CotasFundo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmprestimoAcao = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoRVDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterfaces.AtivosService.BoletoFuturoDTO))]
    public partial class BoletoRVDTO : ServiceInterfaces.AtivosService.BoletoDTO
    {
        
        private System.Nullable<int> DevolucaoCorretagemField;
        
        private System.Nullable<int> IdAgenteCompensacaoField;
        
        private string IdBolsaField;
        
        private System.Nullable<int> TipoCorretagemField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.TipoAtivo> TipoRVField;
        
        private System.Nullable<double> ValorDevolucaoCorretagemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevolucaoCorretagem
        {
            get
            {
                return this.DevolucaoCorretagemField;
            }
            set
            {
                this.DevolucaoCorretagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdAgenteCompensacao
        {
            get
            {
                return this.IdAgenteCompensacaoField;
            }
            set
            {
                this.IdAgenteCompensacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdBolsa
        {
            get
            {
                return this.IdBolsaField;
            }
            set
            {
                this.IdBolsaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoCorretagem
        {
            get
            {
                return this.TipoCorretagemField;
            }
            set
            {
                this.TipoCorretagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.TipoAtivo> TipoRV
        {
            get
            {
                return this.TipoRVField;
            }
            set
            {
                this.TipoRVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorDevolucaoCorretagem
        {
            get
            {
                return this.ValorDevolucaoCorretagemField;
            }
            set
            {
                this.ValorDevolucaoCorretagemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterfaces.AtivosService.BoletoRFDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterfaces.AtivosService.BoletoAdelicDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterfaces.AtivosService.BoletoRVDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceInterfaces.AtivosService.BoletoFuturoDTO))]
    public partial class BoletoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.Clearing> ClearingField;
        
        private string CodigoExternoField;
        
        private System.DateTime DataBoletoField;
        
        private System.DateTime DataVencimentoField;
        
        private System.Nullable<int> IdArquivoBoletoField;
        
        private System.Nullable<int> IdBoletoField;
        
        private System.Nullable<int> IdCarteiraField;
        
        private System.Nullable<int> IdCorretoraField;
        
        private System.Nullable<int> IdInstrFinField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.LocalCustodia> LocalCustodiaField;
        
        private System.Nullable<double> PUField;
        
        private System.Nullable<double> QuantidadeField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.StatusBoleto> StatusBoletoField;
        
        private System.Nullable<int> TipoBoletoField;
        
        private System.Nullable<ServiceInterfaces.AtivosService.TipoLiqFin> TipoLiqFinField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.Clearing> Clearing
        {
            get
            {
                return this.ClearingField;
            }
            set
            {
                this.ClearingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoExterno
        {
            get
            {
                return this.CodigoExternoField;
            }
            set
            {
                this.CodigoExternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataBoleto
        {
            get
            {
                return this.DataBoletoField;
            }
            set
            {
                this.DataBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataVencimento
        {
            get
            {
                return this.DataVencimentoField;
            }
            set
            {
                this.DataVencimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdArquivoBoleto
        {
            get
            {
                return this.IdArquivoBoletoField;
            }
            set
            {
                this.IdArquivoBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdBoleto
        {
            get
            {
                return this.IdBoletoField;
            }
            set
            {
                this.IdBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCarteira
        {
            get
            {
                return this.IdCarteiraField;
            }
            set
            {
                this.IdCarteiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCorretora
        {
            get
            {
                return this.IdCorretoraField;
            }
            set
            {
                this.IdCorretoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdInstrFin
        {
            get
            {
                return this.IdInstrFinField;
            }
            set
            {
                this.IdInstrFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.LocalCustodia> LocalCustodia
        {
            get
            {
                return this.LocalCustodiaField;
            }
            set
            {
                this.LocalCustodiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PU
        {
            get
            {
                return this.PUField;
            }
            set
            {
                this.PUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.StatusBoleto> StatusBoleto
        {
            get
            {
                return this.StatusBoletoField;
            }
            set
            {
                this.StatusBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoBoleto
        {
            get
            {
                return this.TipoBoletoField;
            }
            set
            {
                this.TipoBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceInterfaces.AtivosService.TipoLiqFin> TipoLiqFin
        {
            get
            {
                return this.TipoLiqFinField;
            }
            set
            {
                this.TipoLiqFinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoRFDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    public partial class BoletoRFDTO : ServiceInterfaces.AtivosService.BoletoDTO
    {
        
        private System.Nullable<int> ComandoField;
        
        private System.Nullable<int> ComandoOriginalField;
        
        private System.DateTime DtLiqTermoField;
        
        private System.Nullable<bool> EAdelicField;
        
        private System.Nullable<bool> EDayTradeField;
        
        private System.Nullable<bool> ETermoField;
        
        private System.Nullable<int> IdContraParteField;
        
        private System.Nullable<int> IdNotaResgatadaField;
        
        private System.Nullable<int> TipoNegociacaoField;
        
        private System.Nullable<int> TipoOperacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Comando
        {
            get
            {
                return this.ComandoField;
            }
            set
            {
                this.ComandoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ComandoOriginal
        {
            get
            {
                return this.ComandoOriginalField;
            }
            set
            {
                this.ComandoOriginalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtLiqTermo
        {
            get
            {
                return this.DtLiqTermoField;
            }
            set
            {
                this.DtLiqTermoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EAdelic
        {
            get
            {
                return this.EAdelicField;
            }
            set
            {
                this.EAdelicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EDayTrade
        {
            get
            {
                return this.EDayTradeField;
            }
            set
            {
                this.EDayTradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ETermo
        {
            get
            {
                return this.ETermoField;
            }
            set
            {
                this.ETermoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdContraParte
        {
            get
            {
                return this.IdContraParteField;
            }
            set
            {
                this.IdContraParteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdNotaResgatada
        {
            get
            {
                return this.IdNotaResgatadaField;
            }
            set
            {
                this.IdNotaResgatadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoNegociacao
        {
            get
            {
                return this.TipoNegociacaoField;
            }
            set
            {
                this.TipoNegociacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoOperacao
        {
            get
            {
                return this.TipoOperacaoField;
            }
            set
            {
                this.TipoOperacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoAdelicDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    public partial class BoletoAdelicDTO : ServiceInterfaces.AtivosService.BoletoDTO
    {
        
        private System.Nullable<int> ComandoField;
        
        private System.DateTime DataRetornoField;
        
        private System.Nullable<int> IdContraParteField;
        
        private System.Nullable<int> IdIndexadorField;
        
        private System.Nullable<double> PercentualIndexadorField;
        
        private System.Nullable<int> PrazoField;
        
        private System.Nullable<double> PuIdaField;
        
        private System.Nullable<double> PuRetornoField;
        
        private System.Nullable<double> TaxaAnoField;
        
        private System.Nullable<double> ValorIdaField;
        
        private System.Nullable<double> ValorRetornoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Comando
        {
            get
            {
                return this.ComandoField;
            }
            set
            {
                this.ComandoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataRetorno
        {
            get
            {
                return this.DataRetornoField;
            }
            set
            {
                this.DataRetornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdContraParte
        {
            get
            {
                return this.IdContraParteField;
            }
            set
            {
                this.IdContraParteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdIndexador
        {
            get
            {
                return this.IdIndexadorField;
            }
            set
            {
                this.IdIndexadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PercentualIndexador
        {
            get
            {
                return this.PercentualIndexadorField;
            }
            set
            {
                this.PercentualIndexadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Prazo
        {
            get
            {
                return this.PrazoField;
            }
            set
            {
                this.PrazoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PuIda
        {
            get
            {
                return this.PuIdaField;
            }
            set
            {
                this.PuIdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PuRetorno
        {
            get
            {
                return this.PuRetornoField;
            }
            set
            {
                this.PuRetornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TaxaAno
        {
            get
            {
                return this.TaxaAnoField;
            }
            set
            {
                this.TaxaAnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorIda
        {
            get
            {
                return this.ValorIdaField;
            }
            set
            {
                this.ValorIdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValorRetorno
        {
            get
            {
                return this.ValorRetornoField;
            }
            set
            {
                this.ValorRetornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoletoFuturoDTO", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    public partial class BoletoFuturoDTO : ServiceInterfaces.AtivosService.BoletoRVDTO
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clearing", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum Clearing : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Central = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CBLC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMFDerivativos = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELIC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CETIP = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalCustodia", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum LocalCustodia : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CETIP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMeF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nenhum = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELIC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADM = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTC = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusBoleto", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum StatusBoleto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bloqueado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Errado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendenteGestor = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejeitado = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendenteHorario = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmAprovacao = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprovado = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnviadoCustodiante = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoLiqFin", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum TipoLiqFin : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CETIP = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELIC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAtivo", Namespace="http://schemas.datacontract.org/2004/07/CadAtivos.WSClient.CadAtivosWS")]
    public enum TipoAtivo : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acao = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpcaoAcao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpcaoFuturo = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Futuro = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Termo = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoOperacaoBoletos", Namespace="http://schemas.datacontract.org/2004/07/AtivosService.BusinessRules")]
    public partial class RetornoOperacaoBoletos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QtdAprovadosField;
        
        private int QtdBloqueadosField;
        
        private int QtdCanceladosField;
        
        private int QtdExcluidosField;
        
        private int QtdTotalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdAprovados
        {
            get
            {
                return this.QtdAprovadosField;
            }
            set
            {
                this.QtdAprovadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdBloqueados
        {
            get
            {
                return this.QtdBloqueadosField;
            }
            set
            {
                this.QtdBloqueadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdCancelados
        {
            get
            {
                return this.QtdCanceladosField;
            }
            set
            {
                this.QtdCanceladosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdExcluidos
        {
            get
            {
                return this.QtdExcluidosField;
            }
            set
            {
                this.QtdExcluidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdTotal
        {
            get
            {
                return this.QtdTotalField;
            }
            set
            {
                this.QtdTotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInterfaces.AtivosService.IAtivosService")]
    public interface IAtivosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/UploadArquivoBoleto", ReplyAction="http://tempuri.org/IAtivosService/UploadArquivoBoletoResponse")]
        string UploadArquivoBoleto(string nomeArquivo, byte[] dadosArquivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ConsultarArquivoBoleto", ReplyAction="http://tempuri.org/IAtivosService/ConsultarArquivoBoletoResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ConsultarArquivoBoleto(out ServiceInterfaces.AtivosService.ArquivoBoletoDTO arquivoBoleto, string hash, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ConsultaBoletosRV", ReplyAction="http://tempuri.org/IAtivosService/ConsultaBoletosRVResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosRV(out ServiceInterfaces.AtivosService.BoletoRVDTO[] listaBoletosRV, string hash, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ConsultaBoletosFuturo", ReplyAction="http://tempuri.org/IAtivosService/ConsultaBoletosFuturoResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosFuturo(out ServiceInterfaces.AtivosService.BoletoFuturoDTO[] listaBoletosFuturo, string hash, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ConsultaBoletosRF", ReplyAction="http://tempuri.org/IAtivosService/ConsultaBoletosRFResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosRF(out ServiceInterfaces.AtivosService.BoletoRFDTO[] listaBoletosRF, string hash, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ConsultaBoletosAdelic", ReplyAction="http://tempuri.org/IAtivosService/ConsultaBoletosAdelicResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosAdelic(out ServiceInterfaces.AtivosService.BoletoAdelicDTO[] listaBoletosAdelic, string hash, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/ExcluirBoletosPorArquivo", ReplyAction="http://tempuri.org/IAtivosService/ExcluirBoletosPorArquivoResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService ExcluirBoletosPorArquivo(out ServiceInterfaces.AtivosService.RetornoOperacaoBoletos retornoOperacao, int idArquivoBoleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtivosService/BloquearBoletosPorArquivo", ReplyAction="http://tempuri.org/IAtivosService/BloquearBoletosPorArquivoResponse")]
        ServiceInterfaces.AtivosService.RetornoWebService BloquearBoletosPorArquivo(out ServiceInterfaces.AtivosService.RetornoOperacaoBoletos retornoOperacao, int idArquivoBoleto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAtivosServiceChannel : ServiceInterfaces.AtivosService.IAtivosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtivosServiceClient : System.ServiceModel.ClientBase<ServiceInterfaces.AtivosService.IAtivosService>, ServiceInterfaces.AtivosService.IAtivosService
    {
        
        public AtivosServiceClient()
        {
        }
        
        public AtivosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AtivosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AtivosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AtivosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string UploadArquivoBoleto(string nomeArquivo, byte[] dadosArquivo)
        {
            return base.Channel.UploadArquivoBoleto(nomeArquivo, dadosArquivo);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ConsultarArquivoBoleto(out ServiceInterfaces.AtivosService.ArquivoBoletoDTO arquivoBoleto, string hash, int idArquivoBoleto)
        {
            return base.Channel.ConsultarArquivoBoleto(out arquivoBoleto, hash, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosRV(out ServiceInterfaces.AtivosService.BoletoRVDTO[] listaBoletosRV, string hash, int idArquivoBoleto)
        {
            return base.Channel.ConsultaBoletosRV(out listaBoletosRV, hash, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosFuturo(out ServiceInterfaces.AtivosService.BoletoFuturoDTO[] listaBoletosFuturo, string hash, int idArquivoBoleto)
        {
            return base.Channel.ConsultaBoletosFuturo(out listaBoletosFuturo, hash, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosRF(out ServiceInterfaces.AtivosService.BoletoRFDTO[] listaBoletosRF, string hash, int idArquivoBoleto)
        {
            return base.Channel.ConsultaBoletosRF(out listaBoletosRF, hash, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ConsultaBoletosAdelic(out ServiceInterfaces.AtivosService.BoletoAdelicDTO[] listaBoletosAdelic, string hash, int idArquivoBoleto)
        {
            return base.Channel.ConsultaBoletosAdelic(out listaBoletosAdelic, hash, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService ExcluirBoletosPorArquivo(out ServiceInterfaces.AtivosService.RetornoOperacaoBoletos retornoOperacao, int idArquivoBoleto)
        {
            return base.Channel.ExcluirBoletosPorArquivo(out retornoOperacao, idArquivoBoleto);
        }
        
        public ServiceInterfaces.AtivosService.RetornoWebService BloquearBoletosPorArquivo(out ServiceInterfaces.AtivosService.RetornoOperacaoBoletos retornoOperacao, int idArquivoBoleto)
        {
            return base.Channel.BloquearBoletosPorArquivo(out retornoOperacao, idArquivoBoleto);
        }
    }
}
