//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInterfaces.CadastroService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoWebService", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public partial class RetornoWebService : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string MensagemField;
        
        private ServiceInterfaces.CadastroService.eStatusRetorno StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.CadastroService.eStatusRetorno Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eStatusRetorno", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public enum eStatusRetorno : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportacaoClienteWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class ExportacaoClienteWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ServiceInterfaces.CadastroService.TitularidadeWseDTO[] titularidadesFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.TitularidadeWseDTO[] titularidadesField
        {
            get
            {
                return this.titularidadesFieldField;
            }
            set
            {
                this.titularidadesFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TitularidadeWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class TitularidadeWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string classificacaoTributariaFieldField;
        
        private ServiceInterfaces.CadastroService.ContaExternaWseDTO[] contasExternasFieldField;
        
        private ServiceInterfaces.CadastroService.ContaWseDTO[] contasFieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO cotitular1FieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO cotitular2FieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO cotitular3FieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO cotitular4FieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO cotitular5FieldField;
        
        private System.DateTime dataFimFieldField;
        
        private System.DateTime dataInicioFieldField;
        
        private string faixaPatrimonialFieldField;
        
        private string faixaRemuneracaoFieldField;
        
        private string tipoTitularidadeFieldField;
        
        private ServiceInterfaces.CadastroService.PessoaWseDTO titularFieldField;
        
        private bool transmitirOrdemEscritaFaxEmailFieldField;
        
        private bool transmitirOrdemVerbalFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string classificacaoTributariaField
        {
            get
            {
                return this.classificacaoTributariaFieldField;
            }
            set
            {
                this.classificacaoTributariaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.ContaExternaWseDTO[] contasExternasField
        {
            get
            {
                return this.contasExternasFieldField;
            }
            set
            {
                this.contasExternasFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.ContaWseDTO[] contasField
        {
            get
            {
                return this.contasFieldField;
            }
            set
            {
                this.contasFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO cotitular1Field
        {
            get
            {
                return this.cotitular1FieldField;
            }
            set
            {
                this.cotitular1FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO cotitular2Field
        {
            get
            {
                return this.cotitular2FieldField;
            }
            set
            {
                this.cotitular2FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO cotitular3Field
        {
            get
            {
                return this.cotitular3FieldField;
            }
            set
            {
                this.cotitular3FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO cotitular4Field
        {
            get
            {
                return this.cotitular4FieldField;
            }
            set
            {
                this.cotitular4FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO cotitular5Field
        {
            get
            {
                return this.cotitular5FieldField;
            }
            set
            {
                this.cotitular5FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataFimField
        {
            get
            {
                return this.dataFimFieldField;
            }
            set
            {
                this.dataFimFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataInicioField
        {
            get
            {
                return this.dataInicioFieldField;
            }
            set
            {
                this.dataInicioFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string faixaPatrimonialField
        {
            get
            {
                return this.faixaPatrimonialFieldField;
            }
            set
            {
                this.faixaPatrimonialFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string faixaRemuneracaoField
        {
            get
            {
                return this.faixaRemuneracaoFieldField;
            }
            set
            {
                this.faixaRemuneracaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoTitularidadeField
        {
            get
            {
                return this.tipoTitularidadeFieldField;
            }
            set
            {
                this.tipoTitularidadeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.PessoaWseDTO titularField
        {
            get
            {
                return this.titularFieldField;
            }
            set
            {
                this.titularFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool transmitirOrdemEscritaFaxEmailField
        {
            get
            {
                return this.transmitirOrdemEscritaFaxEmailFieldField;
            }
            set
            {
                this.transmitirOrdemEscritaFaxEmailFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool transmitirOrdemVerbalField
        {
            get
            {
                return this.transmitirOrdemVerbalFieldField;
            }
            set
            {
                this.transmitirOrdemVerbalFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class PessoaWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string apelidoFieldField;
        
        private decimal cPFFieldField;
        
        private string cargoFieldField;
        
        private string conjugeFieldField;
        
        private System.DateTime dataAdmissaoFieldField;
        
        private System.DateTime dataEmissaoRGFieldField;
        
        private System.DateTime dataEspolioFieldField;
        
        private System.DateTime dataNascimentoFieldField;
        
        private ServiceInterfaces.CadastroService.EmailWseDTO[] emailsFieldField;
        
        private string emissorRGFieldField;
        
        private ServiceInterfaces.CadastroService.EnderecoWseDTO[] enderecosFieldField;
        
        private string escolaridadeFieldField;
        
        private string estadoCivilFieldField;
        
        private string filiacaoMaeFieldField;
        
        private string filiacaoPaiFieldField;
        
        private int idPessoaFieldField;
        
        private string naturalidadeFieldField;
        
        private string nomeAbreviadoFieldField;
        
        private string nomeFieldField;
        
        private string numeroRGFieldField;
        
        private string ocupacaoFieldField;
        
        private string paisDomicilioPFFieldField;
        
        private string paisNacionalidadeFieldField;
        
        private string profissaoFieldField;
        
        private string regimeCasamentoFieldField;
        
        private char sexoFieldField;
        
        private string situacaoLegalFieldField;
        
        private ServiceInterfaces.CadastroService.TelefoneWseDTO[] telefonesFieldField;
        
        private string tipoPessoaFieldField;
        
        private string tipoRegistroFieldField;
        
        private string ufrgFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string apelidoField
        {
            get
            {
                return this.apelidoFieldField;
            }
            set
            {
                this.apelidoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal cPFField
        {
            get
            {
                return this.cPFFieldField;
            }
            set
            {
                this.cPFFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cargoField
        {
            get
            {
                return this.cargoFieldField;
            }
            set
            {
                this.cargoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string conjugeField
        {
            get
            {
                return this.conjugeFieldField;
            }
            set
            {
                this.conjugeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataAdmissaoField
        {
            get
            {
                return this.dataAdmissaoFieldField;
            }
            set
            {
                this.dataAdmissaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataEmissaoRGField
        {
            get
            {
                return this.dataEmissaoRGFieldField;
            }
            set
            {
                this.dataEmissaoRGFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataEspolioField
        {
            get
            {
                return this.dataEspolioFieldField;
            }
            set
            {
                this.dataEspolioFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataNascimentoField
        {
            get
            {
                return this.dataNascimentoFieldField;
            }
            set
            {
                this.dataNascimentoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.EmailWseDTO[] emailsField
        {
            get
            {
                return this.emailsFieldField;
            }
            set
            {
                this.emailsFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string emissorRGField
        {
            get
            {
                return this.emissorRGFieldField;
            }
            set
            {
                this.emissorRGFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.EnderecoWseDTO[] enderecosField
        {
            get
            {
                return this.enderecosFieldField;
            }
            set
            {
                this.enderecosFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string escolaridadeField
        {
            get
            {
                return this.escolaridadeFieldField;
            }
            set
            {
                this.escolaridadeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string estadoCivilField
        {
            get
            {
                return this.estadoCivilFieldField;
            }
            set
            {
                this.estadoCivilFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string filiacaoMaeField
        {
            get
            {
                return this.filiacaoMaeFieldField;
            }
            set
            {
                this.filiacaoMaeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string filiacaoPaiField
        {
            get
            {
                return this.filiacaoPaiFieldField;
            }
            set
            {
                this.filiacaoPaiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idPessoaField
        {
            get
            {
                return this.idPessoaFieldField;
            }
            set
            {
                this.idPessoaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string naturalidadeField
        {
            get
            {
                return this.naturalidadeFieldField;
            }
            set
            {
                this.naturalidadeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeAbreviadoField
        {
            get
            {
                return this.nomeAbreviadoFieldField;
            }
            set
            {
                this.nomeAbreviadoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeField
        {
            get
            {
                return this.nomeFieldField;
            }
            set
            {
                this.nomeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroRGField
        {
            get
            {
                return this.numeroRGFieldField;
            }
            set
            {
                this.numeroRGFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ocupacaoField
        {
            get
            {
                return this.ocupacaoFieldField;
            }
            set
            {
                this.ocupacaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string paisDomicilioPFField
        {
            get
            {
                return this.paisDomicilioPFFieldField;
            }
            set
            {
                this.paisDomicilioPFFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string paisNacionalidadeField
        {
            get
            {
                return this.paisNacionalidadeFieldField;
            }
            set
            {
                this.paisNacionalidadeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string profissaoField
        {
            get
            {
                return this.profissaoFieldField;
            }
            set
            {
                this.profissaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string regimeCasamentoField
        {
            get
            {
                return this.regimeCasamentoFieldField;
            }
            set
            {
                this.regimeCasamentoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char sexoField
        {
            get
            {
                return this.sexoFieldField;
            }
            set
            {
                this.sexoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string situacaoLegalField
        {
            get
            {
                return this.situacaoLegalFieldField;
            }
            set
            {
                this.situacaoLegalFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.TelefoneWseDTO[] telefonesField
        {
            get
            {
                return this.telefonesFieldField;
            }
            set
            {
                this.telefonesFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoPessoaField
        {
            get
            {
                return this.tipoPessoaFieldField;
            }
            set
            {
                this.tipoPessoaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoRegistroField
        {
            get
            {
                return this.tipoRegistroFieldField;
            }
            set
            {
                this.tipoRegistroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ufrgField
        {
            get
            {
                return this.ufrgFieldField;
            }
            set
            {
                this.ufrgFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContaExternaWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class ContaExternaWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ativaFieldField;
        
        private System.DateTime dataAprovacaoFieldField;
        
        private char dvContaExternaFieldField;
        
        private bool eTributadaFieldField;
        
        private string nomeBancoFieldField;
        
        private int numeroAgenciaFieldField;
        
        private int numeroBancoFieldField;
        
        private int numeroFieldField;
        
        private string tipoContaExternaFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ativaField
        {
            get
            {
                return this.ativaFieldField;
            }
            set
            {
                this.ativaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataAprovacaoField
        {
            get
            {
                return this.dataAprovacaoFieldField;
            }
            set
            {
                this.dataAprovacaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char dvContaExternaField
        {
            get
            {
                return this.dvContaExternaFieldField;
            }
            set
            {
                this.dvContaExternaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool eTributadaField
        {
            get
            {
                return this.eTributadaFieldField;
            }
            set
            {
                this.eTributadaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeBancoField
        {
            get
            {
                return this.nomeBancoFieldField;
            }
            set
            {
                this.nomeBancoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroAgenciaField
        {
            get
            {
                return this.numeroAgenciaFieldField;
            }
            set
            {
                this.numeroAgenciaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroBancoField
        {
            get
            {
                return this.numeroBancoFieldField;
            }
            set
            {
                this.numeroBancoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int numeroField
        {
            get
            {
                return this.numeroFieldField;
            }
            set
            {
                this.numeroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoContaExternaField
        {
            get
            {
                return this.tipoContaExternaFieldField;
            }
            set
            {
                this.tipoContaExternaFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContaWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class ContaWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ativaFieldField;
        
        private int cdDistribuidorFieldField;
        
        private int cdOperadorFieldField;
        
        private string classificacaoCVMFieldField;
        
        private System.DateTime dataInicioFieldField;
        
        private bool eBloqueadoFieldField;
        
        private bool eCorrespondenciaExtratoFieldField;
        
        private bool eCorrespondenciaInformeFieldField;
        
        private bool eCorrespondenciaMovimentacaoFieldField;
        
        private ServiceInterfaces.CadastroService.EnderecoWseDTO enderecoContaFieldField;
        
        private int idContaFieldField;
        
        private int idDistribuidorFieldField;
        
        private int idOperadorFieldField;
        
        private string nomeDistribuidorFieldField;
        
        private string nomeOperadorFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ativaField
        {
            get
            {
                return this.ativaFieldField;
            }
            set
            {
                this.ativaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cdDistribuidorField
        {
            get
            {
                return this.cdDistribuidorFieldField;
            }
            set
            {
                this.cdDistribuidorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cdOperadorField
        {
            get
            {
                return this.cdOperadorFieldField;
            }
            set
            {
                this.cdOperadorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string classificacaoCVMField
        {
            get
            {
                return this.classificacaoCVMFieldField;
            }
            set
            {
                this.classificacaoCVMFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataInicioField
        {
            get
            {
                return this.dataInicioFieldField;
            }
            set
            {
                this.dataInicioFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool eBloqueadoField
        {
            get
            {
                return this.eBloqueadoFieldField;
            }
            set
            {
                this.eBloqueadoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool eCorrespondenciaExtratoField
        {
            get
            {
                return this.eCorrespondenciaExtratoFieldField;
            }
            set
            {
                this.eCorrespondenciaExtratoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool eCorrespondenciaInformeField
        {
            get
            {
                return this.eCorrespondenciaInformeFieldField;
            }
            set
            {
                this.eCorrespondenciaInformeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool eCorrespondenciaMovimentacaoField
        {
            get
            {
                return this.eCorrespondenciaMovimentacaoFieldField;
            }
            set
            {
                this.eCorrespondenciaMovimentacaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceInterfaces.CadastroService.EnderecoWseDTO enderecoContaField
        {
            get
            {
                return this.enderecoContaFieldField;
            }
            set
            {
                this.enderecoContaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idContaField
        {
            get
            {
                return this.idContaFieldField;
            }
            set
            {
                this.idContaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idDistribuidorField
        {
            get
            {
                return this.idDistribuidorFieldField;
            }
            set
            {
                this.idDistribuidorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idOperadorField
        {
            get
            {
                return this.idOperadorFieldField;
            }
            set
            {
                this.idOperadorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeDistribuidorField
        {
            get
            {
                return this.nomeDistribuidorFieldField;
            }
            set
            {
                this.nomeDistribuidorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomeOperadorField
        {
            get
            {
                return this.nomeOperadorFieldField;
            }
            set
            {
                this.nomeOperadorFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class EnderecoWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string bairroFieldField;
        
        private string caixaPostalFieldField;
        
        private string cepFieldField;
        
        private string cidadeFieldField;
        
        private string complementoFieldField;
        
        private System.DateTime dataAtualizacaoFieldField;
        
        private System.DateTime dataInclusaoFieldField;
        
        private string logradouroFieldField;
        
        private string numeroFieldField;
        
        private string paisFieldField;
        
        private string pessoaResponsavelFieldField;
        
        private string tipoEnderecoFieldField;
        
        private string ufFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bairroField
        {
            get
            {
                return this.bairroFieldField;
            }
            set
            {
                this.bairroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string caixaPostalField
        {
            get
            {
                return this.caixaPostalFieldField;
            }
            set
            {
                this.caixaPostalFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cepField
        {
            get
            {
                return this.cepFieldField;
            }
            set
            {
                this.cepFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cidadeField
        {
            get
            {
                return this.cidadeFieldField;
            }
            set
            {
                this.cidadeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string complementoField
        {
            get
            {
                return this.complementoFieldField;
            }
            set
            {
                this.complementoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataAtualizacaoField
        {
            get
            {
                return this.dataAtualizacaoFieldField;
            }
            set
            {
                this.dataAtualizacaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dataInclusaoField
        {
            get
            {
                return this.dataInclusaoFieldField;
            }
            set
            {
                this.dataInclusaoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string logradouroField
        {
            get
            {
                return this.logradouroFieldField;
            }
            set
            {
                this.logradouroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroField
        {
            get
            {
                return this.numeroFieldField;
            }
            set
            {
                this.numeroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string paisField
        {
            get
            {
                return this.paisFieldField;
            }
            set
            {
                this.paisFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pessoaResponsavelField
        {
            get
            {
                return this.pessoaResponsavelFieldField;
            }
            set
            {
                this.pessoaResponsavelFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoEnderecoField
        {
            get
            {
                return this.tipoEnderecoFieldField;
            }
            set
            {
                this.tipoEnderecoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ufField
        {
            get
            {
                return this.ufFieldField;
            }
            set
            {
                this.ufFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class EmailWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string emailFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string emailField
        {
            get
            {
                return this.emailFieldField;
            }
            set
            {
                this.emailFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefoneWseDTO", Namespace="http://schemas.datacontract.org/2004/07/Cadastro.WSClient.SMCCadastro")]
    public partial class TelefoneWseDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int dddFieldField;
        
        private int ddiFieldField;
        
        private int fieldDddFieldField;
        
        private int fieldDdiFieldField;
        
        private string numeroFieldField;
        
        private string ramalFieldField;
        
        private string tipoTelefoneFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int dddField
        {
            get
            {
                return this.dddFieldField;
            }
            set
            {
                this.dddFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ddiField
        {
            get
            {
                return this.ddiFieldField;
            }
            set
            {
                this.ddiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int fieldDddField
        {
            get
            {
                return this.fieldDddFieldField;
            }
            set
            {
                this.fieldDddFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int fieldDdiField
        {
            get
            {
                return this.fieldDdiFieldField;
            }
            set
            {
                this.fieldDdiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroField
        {
            get
            {
                return this.numeroFieldField;
            }
            set
            {
                this.numeroFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ramalField
        {
            get
            {
                return this.ramalFieldField;
            }
            set
            {
                this.ramalFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoTelefoneField
        {
            get
            {
                return this.tipoTelefoneFieldField;
            }
            set
            {
                this.tipoTelefoneFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoErroField;
        
        private string MensagemField;
        
        private string OperacaoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoErro
        {
            get
            {
                return this.CodigoErroField;
            }
            set
            {
                this.CodigoErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacao
        {
            get
            {
                return this.OperacaoField;
            }
            set
            {
                this.OperacaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInterfaces.CadastroService.ICadastroService")]
    public interface ICadastroService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICadastroService/RetornaCotistas", ReplyAction="http://tempuri.org/ICadastroService/RetornaCotistasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceInterfaces.CadastroService.FaultMessage), Action="http://tempuri.org/ICadastroService/RetornaCotistasFaultMessageFault", Name="FaultMessage", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
        ServiceInterfaces.CadastroService.RetornoWebService RetornaCotistas(out ServiceInterfaces.CadastroService.ExportacaoClienteWseDTO cotistas, string hash, string nome, decimal[] listaCpfCnpj, System.DateTime dataAPartirDe, System.DateTime dataAte);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICadastroServiceChannel : ServiceInterfaces.CadastroService.ICadastroService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadastroServiceClient : System.ServiceModel.ClientBase<ServiceInterfaces.CadastroService.ICadastroService>, ServiceInterfaces.CadastroService.ICadastroService
    {
        
        public CadastroServiceClient()
        {
        }
        
        public CadastroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CadastroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CadastroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CadastroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceInterfaces.CadastroService.RetornoWebService RetornaCotistas(out ServiceInterfaces.CadastroService.ExportacaoClienteWseDTO cotistas, string hash, string nome, decimal[] listaCpfCnpj, System.DateTime dataAPartirDe, System.DateTime dataAte)
        {
            return base.Channel.RetornaCotistas(out cotistas, hash, nome, listaCpfCnpj, dataAPartirDe, dataAte);
        }
    }
}
