//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInterfaces.CaixaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoWebService", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterfaces.CaixaService")]
    public partial class RetornoWebService : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string MensagemField;
        
        private ServiceInterfaces.CaixaService.eStatusRetorno StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.CaixaService.eStatusRetorno Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eStatusRetorno", Namespace="http://schemas.datacontract.org/2004/07/ServiceInterfaces.CaixaService")]
    public enum eStatusRetorno : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICaixaService")]
public interface ICaixaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaService/UploadOrdensPagamento", ReplyAction="http://tempuri.org/ICaixaService/UploadOrdensPagamentoResponse")]
    ServiceInterfaces.CaixaService.RetornoWebService UploadOrdensPagamento(string nomeArquivo, byte[] dadosArquivo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaService/ConsultaStatusArquivo", ReplyAction="http://tempuri.org/ICaixaService/ConsultaStatusArquivoResponse")]
    ServiceInterfaces.CaixaService.RetornoWebService ConsultaStatusArquivo(string hash, int idArquivo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaService/BuscaExtrato", ReplyAction="http://tempuri.org/ICaixaService/BuscaExtratoResponse")]
    ServiceInterfaces.CaixaService.RetornoWebService BuscaExtrato(out byte[] arquivoBytes, string hash, int idArquivo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaService/ConsultaPagamentos", ReplyAction="http://tempuri.org/ICaixaService/ConsultaPagamentosResponse")]
    ServiceInterfaces.CaixaService.RetornoWebService ConsultaPagamentos(out byte[] arquivoBytes, string hash, int idArquivo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICaixaServiceChannel : ICaixaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CaixaServiceClient : System.ServiceModel.ClientBase<ICaixaService>, ICaixaService
{
    
    public CaixaServiceClient()
    {
    }
    
    public CaixaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CaixaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CaixaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CaixaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ServiceInterfaces.CaixaService.RetornoWebService UploadOrdensPagamento(string nomeArquivo, byte[] dadosArquivo)
    {
        return base.Channel.UploadOrdensPagamento(nomeArquivo, dadosArquivo);
    }
    
    public ServiceInterfaces.CaixaService.RetornoWebService ConsultaStatusArquivo(string hash, int idArquivo)
    {
        return base.Channel.ConsultaStatusArquivo(hash, idArquivo);
    }
    
    public ServiceInterfaces.CaixaService.RetornoWebService BuscaExtrato(out byte[] arquivoBytes, string hash, int idArquivo)
    {
        return base.Channel.BuscaExtrato(out arquivoBytes, hash, idArquivo);
    }
    
    public ServiceInterfaces.CaixaService.RetornoWebService ConsultaPagamentos(out byte[] arquivoBytes, string hash, int idArquivo)
    {
        return base.Channel.ConsultaPagamentos(out arquivoBytes, hash, idArquivo);
    }
}
