//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInterfaces.PassivoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoWebService", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public partial class RetornoWebService : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string MensagemField;
        
        private ServiceInterfaces.PassivoService.eStatusRetorno StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.eStatusRetorno Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eStatusRetorno", Namespace="http://schemas.datacontract.org/2004/07/Notificacao.Facade")]
    public enum eStatusRetorno : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PosicaoContaPorFundo", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class PosicaoContaPorFundo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CdCotistaField;
        
        private System.DateTime DtPosicaoField;
        
        private ServiceInterfaces.PassivoService.FundoPosicaoDTO[] FundosField;
        
        private string NmCotistaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdCotista
        {
            get
            {
                return this.CdCotistaField;
            }
            set
            {
                this.CdCotistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtPosicao
        {
            get
            {
                return this.DtPosicaoField;
            }
            set
            {
                this.DtPosicaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.FundoPosicaoDTO[] Fundos
        {
            get
            {
                return this.FundosField;
            }
            set
            {
                this.FundosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmCotista
        {
            get
            {
                return this.NmCotistaField;
            }
            set
            {
                this.NmCotistaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundoPosicaoDTO", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class FundoPosicaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CdFundoField;
        
        private string NmFundoField;
        
        private ServiceInterfaces.PassivoService.PosicaoDTO[] PosicoesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdFundo
        {
            get
            {
                return this.CdFundoField;
            }
            set
            {
                this.CdFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmFundo
        {
            get
            {
                return this.NmFundoField;
            }
            set
            {
                this.NmFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.PosicaoDTO[] Posicoes
        {
            get
            {
                return this.PosicoesField;
            }
            set
            {
                this.PosicoesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PosicaoDTO", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class PosicaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DtCotaField;
        
        private System.DateTime DtCotizacaoField;
        
        private System.DateTime DtMovimentacaoField;
        
        private string HistoricoField;
        
        private int IdNotaField;
        
        private double QtdBloqueadasField;
        
        private double QtdCotaField;
        
        private double VlAplicacaoOriginalField;
        
        private double VlBrutoField;
        
        private double VlCotaField;
        
        private double VlDescontadaField;
        
        private double VlIOFField;
        
        private double VlIRField;
        
        private double VlLiquidoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCota
        {
            get
            {
                return this.DtCotaField;
            }
            set
            {
                this.DtCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCotizacao
        {
            get
            {
                return this.DtCotizacaoField;
            }
            set
            {
                this.DtCotizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtMovimentacao
        {
            get
            {
                return this.DtMovimentacaoField;
            }
            set
            {
                this.DtMovimentacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Historico
        {
            get
            {
                return this.HistoricoField;
            }
            set
            {
                this.HistoricoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNota
        {
            get
            {
                return this.IdNotaField;
            }
            set
            {
                this.IdNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QtdBloqueadas
        {
            get
            {
                return this.QtdBloqueadasField;
            }
            set
            {
                this.QtdBloqueadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QtdCota
        {
            get
            {
                return this.QtdCotaField;
            }
            set
            {
                this.QtdCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlAplicacaoOriginal
        {
            get
            {
                return this.VlAplicacaoOriginalField;
            }
            set
            {
                this.VlAplicacaoOriginalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlBruto
        {
            get
            {
                return this.VlBrutoField;
            }
            set
            {
                this.VlBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlCota
        {
            get
            {
                return this.VlCotaField;
            }
            set
            {
                this.VlCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlDescontada
        {
            get
            {
                return this.VlDescontadaField;
            }
            set
            {
                this.VlDescontadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlIOF
        {
            get
            {
                return this.VlIOFField;
            }
            set
            {
                this.VlIOFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlIR
        {
            get
            {
                return this.VlIRField;
            }
            set
            {
                this.VlIRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlLiquido
        {
            get
            {
                return this.VlLiquidoField;
            }
            set
            {
                this.VlLiquidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtratoContaPorFundo", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class ExtratoContaPorFundo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CdCotistaField;
        
        private System.DateTime DtFinalField;
        
        private System.DateTime DtInicialField;
        
        private ServiceInterfaces.PassivoService.FundoExtratoDTO[] FundosExtratoField;
        
        private string NmCotistaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdCotista
        {
            get
            {
                return this.CdCotistaField;
            }
            set
            {
                this.CdCotistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtFinal
        {
            get
            {
                return this.DtFinalField;
            }
            set
            {
                this.DtFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtInicial
        {
            get
            {
                return this.DtInicialField;
            }
            set
            {
                this.DtInicialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.FundoExtratoDTO[] FundosExtrato
        {
            get
            {
                return this.FundosExtratoField;
            }
            set
            {
                this.FundosExtratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmCotista
        {
            get
            {
                return this.NmCotistaField;
            }
            set
            {
                this.NmCotistaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundoExtratoDTO", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class FundoExtratoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CdFundoField;
        
        private ServiceInterfaces.PassivoService.MovimentacaoDTO[] MovimentacoesField;
        
        private string NmFundoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CdFundo
        {
            get
            {
                return this.CdFundoField;
            }
            set
            {
                this.CdFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.MovimentacaoDTO[] Movimentacoes
        {
            get
            {
                return this.MovimentacoesField;
            }
            set
            {
                this.MovimentacoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmFundo
        {
            get
            {
                return this.NmFundoField;
            }
            set
            {
                this.NmFundoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimentacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO.ExtratoPo" +
        "rFundoWSE")]
    public partial class MovimentacaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DtCotaField;
        
        private System.DateTime DtCotizacaoField;
        
        private System.DateTime DtMovimentacaoField;
        
        private string HistoricoField;
        
        private int IdNotaField;
        
        private string IdNotaReferenciaField;
        
        private double QtdBloqueadasField;
        
        private double QtdCotaField;
        
        private double VlAplicacaoOriginalField;
        
        private double VlBrutoField;
        
        private double VlCotaField;
        
        private double VlDescontadaField;
        
        private double VlIOFField;
        
        private double VlIRField;
        
        private double VlLiquidoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCota
        {
            get
            {
                return this.DtCotaField;
            }
            set
            {
                this.DtCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtCotizacao
        {
            get
            {
                return this.DtCotizacaoField;
            }
            set
            {
                this.DtCotizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtMovimentacao
        {
            get
            {
                return this.DtMovimentacaoField;
            }
            set
            {
                this.DtMovimentacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Historico
        {
            get
            {
                return this.HistoricoField;
            }
            set
            {
                this.HistoricoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNota
        {
            get
            {
                return this.IdNotaField;
            }
            set
            {
                this.IdNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNotaReferencia
        {
            get
            {
                return this.IdNotaReferenciaField;
            }
            set
            {
                this.IdNotaReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QtdBloqueadas
        {
            get
            {
                return this.QtdBloqueadasField;
            }
            set
            {
                this.QtdBloqueadasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QtdCota
        {
            get
            {
                return this.QtdCotaField;
            }
            set
            {
                this.QtdCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlAplicacaoOriginal
        {
            get
            {
                return this.VlAplicacaoOriginalField;
            }
            set
            {
                this.VlAplicacaoOriginalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlBruto
        {
            get
            {
                return this.VlBrutoField;
            }
            set
            {
                this.VlBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlCota
        {
            get
            {
                return this.VlCotaField;
            }
            set
            {
                this.VlCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlDescontada
        {
            get
            {
                return this.VlDescontadaField;
            }
            set
            {
                this.VlDescontadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlIOF
        {
            get
            {
                return this.VlIOFField;
            }
            set
            {
                this.VlIOFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlIR
        {
            get
            {
                return this.VlIRField;
            }
            set
            {
                this.VlIRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VlLiquido
        {
            get
            {
                return this.VlLiquidoField;
            }
            set
            {
                this.VlLiquidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimentacoesFundo", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO")]
    public partial class MovimentacoesFundo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cnpjFundoField;
        
        private ServiceInterfaces.PassivoService.MovimentacaoDTO1[] movimentacoesField;
        
        private string nomeFundoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnpjFundo
        {
            get
            {
                return this.cnpjFundoField;
            }
            set
            {
                this.cnpjFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceInterfaces.PassivoService.MovimentacaoDTO1[] movimentacoes
        {
            get
            {
                return this.movimentacoesField;
            }
            set
            {
                this.movimentacoesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeFundo
        {
            get
            {
                return this.nomeFundoField;
            }
            set
            {
                this.nomeFundoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimentacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/PassivoServiceBusinessRules.DTO.Movimenta" +
        "coesFundoWSE")]
    public partial class MovimentacaoDTO1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codigoCotistaField;
        
        private int codigoExternoFundoField;
        
        private int codigoOrdemField;
        
        private decimal cpfField;
        
        private System.DateTime dataAgendamentoRegistroField;
        
        private System.DateTime dataCotizacaoField;
        
        private System.DateTime dataLiquidacaoFinanceiraField;
        
        private System.DateTime dataMovimentacaoField;
        
        private string descricaoMovimentacaoField;
        
        private bool eAplicacaoField;
        
        private double iOFField;
        
        private double irField;
        
        private string nomeCotistaField;
        
        private string nomeDistribuidorField;
        
        private string nomeFundoField;
        
        private string nomeOperadorField;
        
        private int numeroNotaField;
        
        private int numeroNotaAplicacaoField;
        
        private double qtdQuotasField;
        
        private double valorBrutoField;
        
        private double valorCotaField;
        
        private double valorLiquidoField;
        
        private double valorPerformanceField;
        
        private double valorRendimentoBrutoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoCotista
        {
            get
            {
                return this.codigoCotistaField;
            }
            set
            {
                this.codigoCotistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoExternoFundo
        {
            get
            {
                return this.codigoExternoFundoField;
            }
            set
            {
                this.codigoExternoFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigoOrdem
        {
            get
            {
                return this.codigoOrdemField;
            }
            set
            {
                this.codigoOrdemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cpf
        {
            get
            {
                return this.cpfField;
            }
            set
            {
                this.cpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataAgendamentoRegistro
        {
            get
            {
                return this.dataAgendamentoRegistroField;
            }
            set
            {
                this.dataAgendamentoRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataCotizacao
        {
            get
            {
                return this.dataCotizacaoField;
            }
            set
            {
                this.dataCotizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataLiquidacaoFinanceira
        {
            get
            {
                return this.dataLiquidacaoFinanceiraField;
            }
            set
            {
                this.dataLiquidacaoFinanceiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dataMovimentacao
        {
            get
            {
                return this.dataMovimentacaoField;
            }
            set
            {
                this.dataMovimentacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricaoMovimentacao
        {
            get
            {
                return this.descricaoMovimentacaoField;
            }
            set
            {
                this.descricaoMovimentacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool eAplicacao
        {
            get
            {
                return this.eAplicacaoField;
            }
            set
            {
                this.eAplicacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double iOF
        {
            get
            {
                return this.iOFField;
            }
            set
            {
                this.iOFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ir
        {
            get
            {
                return this.irField;
            }
            set
            {
                this.irField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeCotista
        {
            get
            {
                return this.nomeCotistaField;
            }
            set
            {
                this.nomeCotistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeDistribuidor
        {
            get
            {
                return this.nomeDistribuidorField;
            }
            set
            {
                this.nomeDistribuidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeFundo
        {
            get
            {
                return this.nomeFundoField;
            }
            set
            {
                this.nomeFundoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomeOperador
        {
            get
            {
                return this.nomeOperadorField;
            }
            set
            {
                this.nomeOperadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroNota
        {
            get
            {
                return this.numeroNotaField;
            }
            set
            {
                this.numeroNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroNotaAplicacao
        {
            get
            {
                return this.numeroNotaAplicacaoField;
            }
            set
            {
                this.numeroNotaAplicacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double qtdQuotas
        {
            get
            {
                return this.qtdQuotasField;
            }
            set
            {
                this.qtdQuotasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorBruto
        {
            get
            {
                return this.valorBrutoField;
            }
            set
            {
                this.valorBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorCota
        {
            get
            {
                return this.valorCotaField;
            }
            set
            {
                this.valorCotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorLiquido
        {
            get
            {
                return this.valorLiquidoField;
            }
            set
            {
                this.valorLiquidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorPerformance
        {
            get
            {
                return this.valorPerformanceField;
            }
            set
            {
                this.valorPerformanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorRendimentoBruto
        {
            get
            {
                return this.valorRendimentoBrutoField;
            }
            set
            {
                this.valorRendimentoBrutoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInterfaces.PassivoService.IPassivoService")]
    public interface IPassivoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassivoService/PosicaoCotistaPorFundo", ReplyAction="http://tempuri.org/IPassivoService/PosicaoCotistaPorFundoResponse")]
        ServiceInterfaces.PassivoService.RetornoWebService PosicaoCotistaPorFundo(out ServiceInterfaces.PassivoService.PosicaoContaPorFundo[] listaPosicaoConta, string hash, int codigoExternoFundo, System.DateTime dataPosicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassivoService/ExtratoCotistaPorFundo", ReplyAction="http://tempuri.org/IPassivoService/ExtratoCotistaPorFundoResponse")]
        ServiceInterfaces.PassivoService.RetornoWebService ExtratoCotistaPorFundo(out ServiceInterfaces.PassivoService.ExtratoContaPorFundo[] listaExtratoContaPorFundo, string hash, int codigoExternoFundo, System.DateTime dtInicial, System.DateTime dtFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassivoService/MovimentacaoCotistaPorFundo", ReplyAction="http://tempuri.org/IPassivoService/MovimentacaoCotistaPorFundoResponse")]
        ServiceInterfaces.PassivoService.RetornoWebService MovimentacaoCotistaPorFundo(out ServiceInterfaces.PassivoService.MovimentacoesFundo movimentacoesFundo, string hash, int codigoExternoFundo, System.DateTime dtInicial, System.DateTime dtFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassivoService/UploadOrdensPassivo", ReplyAction="http://tempuri.org/IPassivoService/UploadOrdensPassivoResponse")]
        string UploadOrdensPassivo(byte[] bytesArquivo, string nomeArquivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassivoServiceChannel : ServiceInterfaces.PassivoService.IPassivoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassivoServiceClient : System.ServiceModel.ClientBase<ServiceInterfaces.PassivoService.IPassivoService>, ServiceInterfaces.PassivoService.IPassivoService
    {
        
        public PassivoServiceClient()
        {
        }
        
        public PassivoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PassivoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PassivoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PassivoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceInterfaces.PassivoService.RetornoWebService PosicaoCotistaPorFundo(out ServiceInterfaces.PassivoService.PosicaoContaPorFundo[] listaPosicaoConta, string hash, int codigoExternoFundo, System.DateTime dataPosicao)
        {
            return base.Channel.PosicaoCotistaPorFundo(out listaPosicaoConta, hash, codigoExternoFundo, dataPosicao);
        }
        
        public ServiceInterfaces.PassivoService.RetornoWebService ExtratoCotistaPorFundo(out ServiceInterfaces.PassivoService.ExtratoContaPorFundo[] listaExtratoContaPorFundo, string hash, int codigoExternoFundo, System.DateTime dtInicial, System.DateTime dtFinal)
        {
            return base.Channel.ExtratoCotistaPorFundo(out listaExtratoContaPorFundo, hash, codigoExternoFundo, dtInicial, dtFinal);
        }
        
        public ServiceInterfaces.PassivoService.RetornoWebService MovimentacaoCotistaPorFundo(out ServiceInterfaces.PassivoService.MovimentacoesFundo movimentacoesFundo, string hash, int codigoExternoFundo, System.DateTime dtInicial, System.DateTime dtFinal)
        {
            return base.Channel.MovimentacaoCotistaPorFundo(out movimentacoesFundo, hash, codigoExternoFundo, dtInicial, dtFinal);
        }
        
        public string UploadOrdensPassivo(byte[] bytesArquivo, string nomeArquivo)
        {
            return base.Channel.UploadOrdensPassivo(bytesArquivo, nomeArquivo);
        }
    }
}
