


DELETE FROM NESTIMPORT.dbo.Tb_Mellon_Acoes WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_ContasPagar WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_EmprestimoAcoes WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_Fundos WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_Opcoes WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_RendaFixa WHERE refFileName='NESTBRAVOMASTER_20101209.txt'
DELETE FROM NESTIMPORT.dbo.Tb_Mellon_Tesouraria WHERE refFileName='NESTBRAVOMASTER_20101209.txt'



