SELECT CODCVM, count(*) 
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG 
GROUP BY CODCVM
ORDER BY count(*)  DESC


SELECT *
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG 
WHERE CODCVM=7510
ORDER BY KnowDateTime


/*
SELECT CODCVM, DATADFP, count(*)
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG
GROUP BY CODCVM, DATADFP
ORDER BY count(*) DESC
*/

SELECT *
FROM nestother.dbo.Tb022_CVM_DFP_CONFIG 
WHERE STATUS=3
ORDER BY KnowDateTime