SELECT COUNT(*) FROM nestother.dbo.Tb023_CVM_DFP_HDR
SELECT COUNT(*) FROM nestother.dbo.Tb021_CVM_DFP_CTL
SELECT COUNT(*) FROM nestother.dbo.Tb022_CVM_DFP_CONFIG
SELECT COUNT(*) FROM nestother.dbo.Tb025_CVM_DFP_DATA

/*
SELECT TOP 1 * FROM nestother.dbo.Tb023_CVM_DFP_HDR ORDER BY Id_CTL DESC
SELECT TOP 1 * FROM nestother.dbo.Tb021_CVM_DFP_CTL ORDER BY Id_CTL DESC
SELECT TOP 1 * FROM nestother.dbo.Tb022_CVM_DFP_CONFIG ORDER BY Id_CTL DESC
SELECT TOP 1 * FROM nestother.dbo.Tb025_CVM_DFP_DATA ORDER BY Id_CTL DESC
*/

/*
DECLARE @ZIPNAME varchar(100)
SET @ZIPNAME = '10123_10880_DFP_20011231_000000000.zip'

DELETE FROM nestother.dbo.Tb023_CVM_DFP_HDR WHERE ZipName=@ZIPNAME
DELETE FROM nestother.dbo.Tb021_CVM_DFP_CTL WHERE ZipName=@ZIPNAME
DELETE FROM nestother.dbo.Tb022_CVM_DFP_CONFIG WHERE ZipName=@ZIPNAME
DELETE FROM nestother.dbo.Tb025_CVM_DFP_DATA WHERE ZipName=@ZIPNAME
*/

