SELECT CODCVM, count(*) 
FROM nestother.dbo.Tb022_CVM_ITR_CONFIG 
GROUP BY CODCVM
ORDER BY count(*)  DESC


SELECT *
FROM nestother.dbo.Tb022_CVM_ITR_CONFIG 
WHERE CODCVM=7510
ORDER BY KnowDateTime


/*
SELECT CODCVM, DATAITR, count(*)
FROM nestother.dbo.Tb022_CVM_ITR_CONFIG
GROUP BY CODCVM, DATAITR
ORDER BY count(*) DESC
*/

SELECT *
FROM nestother.dbo.Tb025_CVM_ITR_DATA
WHERE ZipName LIKE '%1225_14168_ITR_20000930_000000000.zip%'